services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile-admin
    ports:
      - 8080:80
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 3000:80
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - 5000:5000
    env_file:
      - .env
