FROM nginx:stable-alpine
COPY ./admin/index.html /usr/share/nginx/html/
COPY ./admin/script.js /usr/share/nginx/html/
COPY ./admin/styles.css /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
